<?php

namespace Orgabat\GameBundle\Repository;

/**
 * CategoryRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{   
    /**
    * Important note : because of some unknow error (maybe context issue) this doesn't work
    * in PDFController. There's some random shuffle between exercisesHistory owner.
    * This work fine when printing result for one user.
    * For PDF we used instead ExerciseHistoryRepository::getAllHistoryExercicesByUser
    *
    * Debug has been done by comparing the result of the raw computed dql request (using ->getSql()) which work fine and the pdo request from below which is not fine.
    *
    */
    public function getExercisesOfAllCategoriesByUser($user)
    {
        return $this->createQueryBuilder('c')
            ->join('c.exercises', 'e')
            ->addSelect('e')
            ->join('e.exerciseHistories', 'eh', 'WITH', 'eh.user = :user')
            ->setParameter('user', $user)
            ->addSelect('eh')
            ->addOrderBy('c.id', 'ASC')
            ->addOrderBy('e.id', 'ASC')
            ->addOrderBy('eh.date', 'DESC')
            ->getQuery()
            ->getResult()
        ;
    }
}
